name: Run IPO Alerts

on:
  # Spustí workflow manuálne cez tlačidlo "Run workflow"
  workflow_dispatch:

  # Spustí workflow podľa plánu (každých 15 minút)
  schedule:
    - cron: '0 */15 * * *'  # Spúšťa workflow každých 15 minút

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Checkout kódu
      - name: Checkout code
        uses: actions/checkout@v2

      # Nastavenie Python prostredia
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Inštalácia závislostí
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Spustenie Python skriptu
      - name: Run main.py
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}  # Telegram bot token
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}  # Telegram chat ID
        run: |
          python main.py
