name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # Alebo verzia Pythonu, ktorú používaš

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Nainštaluje všetky závislosti zo súboru requirements.txt

    - name: Run the script
      run: |
        python main.py  # Spustí tvoj hlavný program
