name: IPO Alerts
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: ipo-alerts
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run alerts
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          WATCH_TICKERS: "GTLB,ABNB,PLTR"
          ALERT_ENABLE_IPO: "1"
          ALERT_ENABLE_PRELOCKUP: "0"
          ALERT_FREQ_MIN: "10"
        run: python main.py
